#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Rule {
    Expression,
    FunctionDef,
    FunctionDefParameters,
    BraceExpression,
    BraceStatements,
    Statement,
    IfElse,
    ForLoop,
    Equality,
    Comparison,
    PlusMinus,
    MultDiv,
    Unary,
    FunctionCall,
    FunctionArguments,
    Primary,
    Terminal,
}
